apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: premium-rwo
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  # Removed potentially problematic selectors
  # Simplified recurring jobs configuration
  recurringJobs: '[{"name":"snapshot","task":"snapshot","cron":"0 0 * * *","retain":7}]'