---
apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-values
data:
  values.yaml: |
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    nameOverride: prod
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: class
                  operator: In
                  values:
                    - heavy
    initContainers:
      - name: dd-agent-dl
        image: itzg/minecraft-server:2025.2.1-java17-graalvm
        command: ['bash', '-c', 'curl -sL https://dtdg.co/latest-java-tracer > /data/dd-java-agent.jar']
        volumeMounts:
          - name: datadir
            mountPath: /data
    image:
      repository: itzg/minecraft-server
      tag: 2025.2.1-java23-graalvm
    persistence:
      dataDir:
        enabled: false
    resources:
      requests:
        memory: 10Gi
    extraEnv:
      A_MC_VERSION: "1.20.1"
      A_MP_BUILD: "56"
      A_MP_MASTER: master-prod
      DD_ENV: mk-mp
      DD_VERSION: "$(A_MC_VERSION)#$(A_MP_BUILD)"
      DD_PROFILING_ENABLED: "true"
      DD_LOGS_INJECTION: "true"
      DD_APPSEC_ENABLED: "true"
      ENABLE_JMX: "false"
      ENFORCE_SECURE_PROFILE: "false"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "false"
      ALLOW_FLIGHT: "true"
      SNOOPER_ENABLED: "false"
      USE_AIKAR_FLAGS: "false"
      PAPER_DOWNLOAD_URL: "https://api.multipaper.io/v2/projects/multipaper/versions/$(A_MC_VERSION)/builds/$(A_MP_BUILD)/downloads/multipaper-$(A_MC_VERSION)-$(A_MP_BUILD).jar"
      PACKWIZ_URL: "https://marcusk-studio.github.io/modpacks/space/pack.toml"
      DD_AGENT_HOST:
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      REPLACE_ENV_VARIABLES: "true"
      ENV_VARIABLE_PREFIX: "CFG_"
      CFG_HOST: "worker-prod"
      A_DD_SERVICE: worker
      DD_SERVICE: "$(A_DD_SERVICE)"
      DD_TAGS: &tags "pod:$(A_DD_SERVICE)"
      DD_DOGSTATSD_HOST: datadog.monitoring
      DD_DOGSTATSD_TAGS: *tags
      DD_POD_NAME:
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name
      JMX_HOST:
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      JVM_OPTS: >-
        -XX:+UnlockExperimentalVMOptions
        -XX:+UnlockDiagnosticVMOptions
        -XX:+AlwaysActAsServerClassMachine
        -XX:+AlwaysPreTouch
        -XX:+DisableExplicitGC
        -XX:+UseNUMA
        -XX:NmethodSweepActivity=1
        -XX:ReservedCodeCacheSize=400M
        -XX:NonNMethodCodeHeapSize=12M
        -XX:ProfiledCodeHeapSize=194M
        -XX:NonProfiledCodeHeapSize=194M
        -XX:-DontCompileHugeMethods
        -XX:+PerfDisableSharedMem
        -XX:+UseFastUnorderedTimeStamps
        -XX:+UseCriticalJavaThreadPriority
        -XX:+EagerJVMCI
        -XX:+UseZGC
        -XX:AllocatePrefetchStyle=1
        -XX:-ZProactive
        -XX:ConcGCThreads=8
        -XX:FlightRecorderOptions=stackdepth=256
        -DmultipaperMasterAddress=$(A_MP_MASTER)-multipaper:35353
        -Dmultipaper.master-connection.my-name=$(DD_POD_NAME)
        -Dspigot.settings.bungeecord=true
        -Dserver.address=$(JMX_HOST)
        -javaagent:dd-java-agent.jar
        -Dluckperms.data.mongodb-connection-uri=mongodb://mongodb-headless.default/luckperms?replicaset=rs0&retryWrites=true&w=majority
        -Dluckperms.redis.address=redis-headless.default
    startupProbe:
      enabled: true
      failureThreshold: 40
    minecraftServer:
      eula: true
      onlineMode: false
      gameMode: survival
      forcegameMode: false
      type: &type PAPER
      pvp: true
      forceReDownload: true
      difficulty: easy
      levelType: DEFAULT
      allowNether: true
      playerIdleTimeout: 300
      spawnProtection: 0
      maxWorldSize: 29999984
      maxPlayers: 360
      viewDistance: 10
      maxTickTime: -1
      memory: 8G
      motd: *type
      overrideServerProperties: true
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
