apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: this field is ignored, but required
  namespace: this field is ignored, but required
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age