---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app redis
  namespace: flux-system
spec:
  targetNamespace: default
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/default/redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: marcuskube
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
