---
clusterName: leafycluster
talosVersion: v1.9.6
allowSchedulingOnControlPlanes: true
endpoint: https://leafyplane:6443
nodes:
  - hostname: leafyplane
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
          - TS_ROUTES=10.96.0.0/12
          - TS_AUTH_ONCE=true
    ipAddress: leafyplane
    controlPlane: true
    installDisk: /dev/nvme0n1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/iscsi-tools
            - siderolabs/tailscale
            - siderolabs/util-linux-tools
  - hostname: leafynode
    extensionServices:
      - name: tailscale
        environment:
          - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
          - TS_ROUTES=10.96.0.0/12
          - TS_AUTH_ONCE=true
    ipAddress: leafynode
    controlPlane: false
    installDisk: /dev/nvme0n1
    schematic:
      customization:
        systemExtensions:
          officialExtensions: 
            - siderolabs/iscsi-tools
            - siderolabs/tailscale
            - siderolabs/util-linux-tools
patches:
  - "@./patch-longhorn.yaml"  
  - "@./patch-cilium.yaml"  
