---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-values
data:
  values.yaml: |
    arbiter:
      affinity: &affinity
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: class
                operator: In
                values:
                  - heavy
    affinity: *affinity
    architecture: replicaset
    auth:
      enabled: false
      usernames:
        - luckperms
      databases:
        - luckperms
    persistence:
      storageClass: longhorn
    replicaCount: 3
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: mongodb
