---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-values
data:
  values.yaml: |
    auth:
      rootPassword: password
    primary:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: class
                operator: In
                values:
                  - heavy
      extraFlags: "--max_connections=500"
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
