---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: mariadb
      version: 14.1.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - name: mariadb-values
      kind: ConfigMap
      valuesKey: values.yaml
