---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: datadog
      version: 3.106.1
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - name: datadog-values
      kind: ConfigMap
      valuesKey: values.yaml
