---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-values
data:
  values.yaml: |
    auth:
      enabled: false
    commonLabels: &label
      group: redis
    master:
      nodeAffinityPreset: &affinity
        type: hard
        key: class
        values:
          - heavy
    replica:
      nodeAffinityPreset: *affinity
      replicaCount: 3
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels: *label
