---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-files
data:
  forwarding.secret: |-
    eQE7XnJEBE55
  velocity.toml: |
    announce-forge = false
    bind = "0.0.0.0:25577"
    config-version = "2.7"
    enable-player-address-logging = true
    force-key-authentication = false
    forwarding-secret-file = "forwarding.secret"
    kick-existing-players = false
    motd = "<bold> <gray>   ˙ ⊹ ⋅      ⊹       <dark_gray>[<white>Solar System<dark_gray>] <gray>       ⊹    ˙   ✧    ⊹</bold><reset> <bold>  <gray>      ⋅         ⊹    <gold>By Marcusk<gray>   ⊹     ⋅        ⋅</bold>"
    online-mode = true
    ping-passthrough = "DISABLED"
    player-info-forwarding-mode = "legacy"
    prevent-client-proxy-connections = true
    show-max-players = 1500
    forced-hosts = {}

    [advanced]
      read-timeout = 30000
      tcp-fast-open = true
      compression-level = -1
      compression-threshold = 256
      login-ratelimit = 3000
      connection-timeout = 5000
      log-player-connections = true
      bungee-plugin-message-channel = true
      show-ping-requests = false
      accepts-transfers = false
      failover-on-unexpected-server-disconnect = true
      announce-proxy-commands = true
      haproxy-protocol = false
      log-command-executions = true
    [query]
      port = 25575
      show-plugins = false
      map = "Velocity"
      enabled = true
    [servers]
      KubernetesLB = "worker-prod:25565"
      worker15L = "worker-prod:25565"
      worker17N = "worker-prod:25565"
      try = ["worker15L", "worker17N", "KubernetesLB"]
