---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.8.3
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  valuesFrom:
    - name: ingress-values
      kind: ConfigMap
      valuesKey: values.yaml
